# Generated by Django 3.0.6 on 2020-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='info',
            field=models.TextField(),
        ),
    ]
