# Generated by Django 3.0.6 on 2020-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='coolStuff',
            field=models.BooleanField(default=False),
        ),
    ]
